### ISSUE TITLE
Mapping for a regoin error

### ISSUE THREAD

**Issue by microcreators** [willjasen/rainstash#13]
Any idea about the origin of:
Template validation error: Template error: Unable to get mapping for RegionMap::us-west-1::AMI

Just started playing with AWS and the template. Thanks!

**Comment by willjasen** [comment]
Only the us-east-1 region had a mapping for an AMI ID, so running the template in other regions wouldn't work.

I've added both us-west-1 and us-west-2 at the commit https://github.com/willjasen/rainstash/commit/a3d051edac4d9a797caee72f2d4b2be1bf6b587b and adding other regions is easy. Amazon does occasionally update AMIs and their IDs.

Enjoy!

**Comment by rameshummadisetty** [comment]
Nice Help.
